name: Beta

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@igorkamyshev'
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
        shell: sh
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - run: node ./tools/scripts/restore_beta_versions.mjs
      - run: pnpm changeset pre enter ${{ steps.extract_branch.outputs.branch }}
      - run: pnpm changeset version
      - run: pnpm changeset pre exit
      - run: pnpm nx run-many --output-style=static --target=publish --all --configuration=beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
